---
name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Publish Docs

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
          token: '${{ secrets.GH_PUSH_TOKEN }}'
      - name: Checkout registry repository
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-registry
          path: registry
          fetch-depth: 0
          token: '${{ secrets.GH_PUSH_TOKEN }}'

      - name: Copy Docs
        run: |
          mkdir -p registry/themes/default/content/registry/packages
          rm -rf registry/themes/default/content/registry/packages/proxmoxve
          cp -r main/docs registry/themes/default/content/registry/packages/proxmoxve

      - name: Push To Registry
        uses: peter-evans/create-pull-request@v3
        with:
          token: '${{ secrets.GH_PUSH_TOKEN }}'
          push-to-fork: muhlba91/pulumi-registry
          path: registry
          commit-message: 'feat(proxmoxve): update documentation'
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: proxmoxve/docs
          delete-branch: true
          branch-suffix: short-commit-hash
          title: '[ProxmoxVE] Update Documentation'
          body: |
            Update documentation for the ProxmoxVE provider.
            
            Repository URL: ${{ github.server_url }}/${{ github.repository }}
            Schema File: [`provider/cmd/pulumi-resource-proxmoxve/schema.json`](${{ github.server_url }}/${{ github.repository }}/provider/cmd/pulumi-resource-proxmoxve/schema.json)
